name: awsoom_nofic_test_hragap
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: ^1.24.0
  awesome_notifications: ^0.7.3
  fluttertoast: ^8.0.3
  awesome_notifications_fcm: ^0.7.3
  shared_preferences: ^2.0.13
  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

